# 第八章 异常



## 8.1 异常的类型



异常的根类型：java.lang.Throwable类型。它有两大子类：Error和Exception。



- Error：是指严重的错误，不应该使用try...catch处理，而应该停下来修正程序或升级硬件。

- Exception：是指合理的应用程序需要避免或处理的异常类型。它有分为两大类： 

- - 运行时异常（非受检异常，即编译器检测不到）：RuntimeException及其子类。

- - 编译时异常（受检异常，编译器会（预警）提醒你"可能"发生xx异常，不表示一定发生）：无论是否发生都要提前编写异常处理代码（要么try...catch，要么throws），否则编译不通过。异常中除了运行时异常剩下的都是编译时异常（包括Exception，Throwable本身都是编译时异常）。



面试题：列出你在开发过程中经常/曾经遇到的异常类型（至少5种）。



```java
ArrayIndexOutOfBoundsException：数组下标越界异常
NullPointerException：空指针异常
ClassCastException：类型转换异常
ArithmeticException：算术异常
InputMismatchException：输入不匹配异常
NumberFormatException：数字格式化异常
....
```



面试题：列出你在开发过程中经常/曾经遇到的错误类型。



```java
OutOfMemoryError：OOM，堆内存溢出
StackOverflowError：栈内存溢出
```



面试题：请编写一段代码演示xx异常/错误。



```java
OutOfMemoryError:
 	public static void main(String[] args) {
        int[] arr = new int[Integer.MAX_VALUE];
    }
StackOverflowError：栈内存溢出
    @Test
    public void test1(){
        test1();
    }
```



## 8.2 异常相关的5个关键字



try,catch,finally,throws, throw



```java
try{
    可能发生异常的代码
}catch(异常类型1 参数名){
	异常处理的代码或异常打印代码
}catch(异常类型2 参数名){
	异常处理的代码或异常打印代码
}
```



执行特点：



（1）try{}中没有发生异常，一个catch都不会执行



（2）try{}中有异常发生，try{}中发生异常的代码剩下的代码都不执行，去找匹配的catch分支，从上往下找匹配的catch，如果上面有一个catch匹配了，下面的catch就不看了，只会进入一个catch分支。只要找到一个catch分支，相当于异常被处理了，代码继续运行try...catch结构下面的代码。



（3）try{}中有异常发生，但是所有catch都不匹配，相当于异常没有处理，结束当前方法的执行，并且异常对象会自动抛给上级。如果上级（调用者）也不处理，上级也会结束，然后继续往上抛，直到main方法，如果main方法也不处理，程序就挂了。



```java
try{
    可能发生异常的代码
}finally{
    必须执行的代码
}

try{
    可能发生异常的代码
}catch(异常类型1 参数名){
	异常处理的代码或异常打印代码
}catch(异常类型2 参数名){
	异常处理的代码或异常打印代码
}finally{
    必须执行的代码
}
```



- 无论try中是否发生异常，finally都要执行。

- 无论catch是否可以捕获异常，finally都要执行。

- 无论try或catch分支中是否有return语句，finally都要执行。

- 如果finally块中也有return语句，会导致try或catch中的return语句的结果无法返回。

- finally块通常是编写资源释放的代码。



throws和throw的区别：



- throws只能出现在方法()后面，表示当前方法没有处理这个异常，需要调用者处理这个异常。throws后面接异常的类型列表，如果有多个异常类型，使用逗号分隔。

- throw只能出现在{方法体}里面，表示在xx条件下手动抛出throw一个异常的对象。只要有throw语句，就表示当前方法可能发生xx异常。如果这个异常对象的类型是运行时异常类型，那么编译器不会提示你要做什么处理。但是如果这个异常对象是编译时异常类型，那么编译器会强制你处理这个异常，处理方式有两种，一种是throws甩给调用者处理，一种是try...catch处理，编译才会通过。

|                | throws                                               | throw                |
| -------------- | ---------------------------------------------------- | -------------------- |
| 使用位置       | 在方法()后面                                         | 在{方法体}里面       |
| 关键字后面跟的 | 异常类型，如果有多个异常类型，使用逗号分隔           | 异常对象             |
| 作用           | 表示当前方法没有处理这个异常，需要调用者处理这个异常 | 主动抛出一个异常对象 |



```java
【修饰符】返回值类型 方法名(【形参列表】)throws 异常类型列表{ //如果异常类型列表有多个类型，可以用逗号分隔
    
    if(){
        throw new 异常类型(【实参类别】);
    }
}
```



## 8.3 自定义异常



要求：



（1）自定义异常是一个“类class”，必须继承Throwable或它的子类。一般是继承如下两个类：



- RuntimeException：如果是继承它，那么说明你这个自定义异常是运行时异常

- Exception：如果是继承它，那么说明你这个自定义异常是编译时异常。如果是这种，一旦方法体中有throw new 自定义异常类型()的代码，就必须加throws或try...catch，否则编译不通过。



（2）建议自定义异常编写两个或以上的构造器



```java
自定义异常类型(){//无参构造
	
}
自定义异常类型(String message){//有参构造
	super(message);
}
```



（3）自定义异常的对象，必须自己new并且使用throw语句抛出。



## 8.4 Java的异常抛出和处理机制



简答：请描述Java的异常抛出和处理机制



（1）当某句代码发生了异常，Java程序执行会暂停，并在这句代码处判断是什么原因发生的异常，JVM会创建一个对应类型的异常对象，并且抛出。如果你手动throw 异常对象，代码执行到这句代码，就相当于发生异常了，JVM也会抛出这个异常对象。



（2）Java异常检测和处理程序，就会判断这句发生异常的代码是否在try的{}，



- 如果是在try的{}中，那么会赶紧找匹配的catch分支处理异常，如果处理成功，那么代码继续执行try...catch整个结构下面的代码。

- 如果是在try的{}中，但是没有catch分支可以匹配这个异常，即没有处理成功，也会让当前方法停止执行，当前方法退出栈，并且把异常对象带回调用处，在调用处重复（2）

- 如果不在try的{}中，那么就会让当前方法停止执行，当前方法退出栈，并且把异常对象带回调用处，在调用处重复（2）



（3）如果所有的调用者都无法处理这个异常，那么JVM就会终止运行。只要有一级调用者可以处理这个异常，那么程序就从处理完的位置继续执行，之前终止的代码就不执行了。



总结：



无论是JVM自动创建的异常对象，还是我们自己throw的异常对象，都要通过try...catch处理。



无论是受检异常还是非受检异常，只要发生了，就必须有try...catch处理，否则程序就会崩溃。只不过受检异常编译器的态度更谨慎一些，要求必须throws或try...catch才能编译通过。



虽然有些方法可以暂时通过throws将异常对象抛给调用者，那也只是表示当前方法不处理，调用者仍然要用try...catch处理，否则如果所有调用者都不处理，也会导致程序终止运行。



## 8.5 方法重写



要求：



（1）方法名：必须相同



（2）形参列表：必须相同



（3）返回值类型



​	基本数据类型和void：必须相同



​	引用数据类型：<=



（4）权限修饰符：>=



被重写方法不能是private，跨包不能是缺省



（5）其他修饰符



不能是final，static



（6）throws的要求



- 如果被重写方法没有throws编译时异常，那么重写方法时，也不能throws编译时异常。

- 如果被重写方法有throws编译时异常，那么重写方法时，可以不throws编译时异常，如果要throws编译时异常，也只能是<=的关系。

- 重写方法对于运行时异常不做任意要求，因为编译时不会检查运行时异常。



```java
这些<=，>=都是考虑多态引用时，编译和运行时都合理的要求。

 class Father{
     protected Animal method()throws Exception{
         return new Animal();
     }
 }
class Son extends Father{
    @Override
    public Dog method()throws RuntimeException{
         return new Dog();
     }
}
class Test{
    public static void main(String[] args){
        Father f = new Son();//多态
        
        try{
            Animal returnValue = f.method();
            //编译时看Father类，以Father类中method方法的签名检查权限修饰符，返回值类型等
            //异常处理，此时也是按照Father类中method方法的签名中的异常类型处理的
            
            //运行时f对象的运行时类型是Son，执行Son中重写的method方法
            //此时Son中的method方法权限修饰符 >= 父类被重写的方法  才是合理的
            //如果此时Son中的method方法权限修饰符是<的话，例如private,那么编译通过，运行会找不到方法执行
            //此时Son中的method方法返回值是Dog类型 < Animal，可以的
            //因为 f.method()的返回值用Animal接收，是安全的
            //但反过来，就会导致编译时用Dog接收，实际返回一个Animal对象，有问题
            
            //异常处理也相同
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
```